### ISSUE TITLE
TST: Line Lists plugin broke in devdeps job

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1039]
39 failed, all with the same cause. Example log: https://github.com/spacetelescope/jdaviz/actions/runs/1684410750

```
___________ ERROR at setup of TestSpecvizHelper.test_load_spectrum1d ___________

self = <jdaviz.configs.specviz.tests.test_helper.TestSpecvizHelper object at 0x7f2ae1321f10>
specviz_app = <jdaviz.configs.specviz.helper.Specviz object at 0x7f2ae1321c70>
spectrum1d = <Spectrum1D(flux=<Quantity [12.49671415, 12.30618014, 13.53658529, 14.85657834, 13.5436244 ,
           13.98808527, 1...28024,
                   1.72491783, 0.56228753, 1.01283112, 0.31424733,
                   0.90802408, 1.4123037 ]))>
...
        # set redshift slider to redshift stored in Spectrum1D object
>       self.rs_redshift = viewer_data.redshift.value
E       AttributeError: 'numpy.float64' object has no attribute 'value'
.../jdaviz/configs/default/plugins/line_lists/line_lists.py:133: AttributeError
...
...
__________________________ [doctest] import_data.rst ___________________________
050 
051     >>> from jdaviz import Specviz
052     >>> import numpy as np
053     >>> import astropy.units as u
054     >>> from specutils import Spectrum1D
055     >>> flux = np.random.randn(200)*u.Jy
056     >>> wavelength = np.arange(5100, 5300)*u.AA
057     >>> spec1d = Spectrum1D(spectral_axis=wavelength, flux=flux)
058     >>> specviz = Specviz()
059     >>> specviz.load_spectrum(spec1d)  # doctest: +IGNORE_OUTPUT
UNEXPECTED EXCEPTION: AttributeError("'numpy.float64' object has no attribute 'value'")
Traceback (most recent call last):
...
  File ".../jdaviz/configs/specviz/helper.py", line 42, in load_spectrum
    super().load_data(data,
  File ".../jdaviz/core/helpers.py", line 61, in load_data
    self.app.load_data(data, parser_reference=parser_reference, **kwargs)
  File ".../jdaviz/app.py", line 362, in load_data
    msg = parser(self, file_obj, **kwargs)
  File ".../jdaviz/configs/specviz/plugins/parsers.py", line 83, in specviz_spectrum1d_parser
    app.add_data_to_viewer("spectrum-viewer", data_label[i])
  File ".../jdaviz/app.py", line 790, in add_data_to_viewer
    self._update_selected_data_items(viewer_item['id'], data_ids)
  File ".../jdaviz/app.py", line 1119, in _update_selected_data_items
    self.hub.broadcast(add_data_message)
  File ".../glue/core/hub.py", line 215, in broadcast
    handler(message)
```

Only happened in the job where we test against dev version of upstream dependencies. @kecnry , since you did a lot of the redshift stuff lately, you have any idea where to look? `specutils` has not been touched but `astropy` dev has been pretty active.

**Comment by pllim** [comment]
Nevermind, I think I know why... astropy/astropy#12738
