### ISSUE TITLE
[BUG] Tornado 'authorizer' error after fresh installation

### ISSUE THREAD

**Issue by jrhastro** [spacetelescope/jdaviz#1170]
**Describe the bug**
After doing a clean install of jdaviz in a new conda environment, the web application will not load and throws a Tornado 'authorizer' warning.

**To Reproduce**
1.  Install jdaviz using the following commands:

```
conda create -n jdaviz python=3.8
conda activate jdaviz
pip install jdaviz --no-cache-dir
```

2. Downloaded example SDSS MaNGA IFU data file
3. Executing the command:

`$jdaviz ./manga-8485-1901-LOGCUBE.fits.gz --layout=cubeviz`

4.  I get the following error message:

```
[Voila] Using /var/folders/wq/b0ymy3v15253byc7kntj80xc0001n8/T to store connection files
[Voila] Storing connection files in /var/folders/wq/b0ymy3v15253byc7kntj80xc0001n8/T/voila_389n5woe.
[Voila] Serving static files from /Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/voila/static.
[Voila] Voilà is running at:
http://localhost:8866/
[Voila] WARNING | Notebook notebook.ipynb is not trusted
[Voila] Kernel started: 3f838089-5109-45ac-b275-cb63111ef5c3
/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/auth/decorator.py:18: UserWarning: The Tornado web application does not have an 'authorizer' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an authorizer to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/653740cbad7ce0c8a8752ce83e4d3c2c754b13cb/jupyter_server/serverapp.py#L234-L256
  warnings.warn(
```

5.  The web application starts but displays a window saying 'Executing Cell 1 of 1'

**Expected behavior**
I expected to see some kind of application interface, but instead it seems like the application hangs and is unable to display the data cube.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.4
 - Browser: Chrome Version 99.0.4844.51 (Official Build) (x86_64)
 - Jupyter:
```$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.1.1
ipykernel        : 6.9.2
ipywidgets       : 7.6.5
jupyter_client   : 7.1.2
jupyter_core     : 4.9.2
jupyter_server   : 1.15.4
jupyterlab       : 3.3.2
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.2.0
notebook         : 6.4.10
qtconsole        : 5.2.2
traitlets        : 5.1.1
```

**Package versions (please complete the following information):**

```
macOS-10.16-x86_64-i386-64bit
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ]
Numpy 1.22.3
astropy 5.0.2
specutils 1.7.0
pyyaml 6.0
click 8.0.4
asteval 0.9.26
idna 3.3
traitlets 5.1.1
bqplot 0.12.33
bqplot-image-gl 1.4.6
glue-core 1.2.4
glue-jupyter 0.10.1
glue-astronomy 0.3.2
echo 0.6
ipyvue 1.7.0
ipyvuetify 1.8.2
ipysplitpanes 0.2.0
ipygoldenlayout 0.4.0
voila 0.3.3
vispy 0.9.6
Jdaviz 2.3.0
```

**Additional context (e.g. data files)**

**Comment by pllim** [comment]
Just to be sure, can you reproduce this from dev version of Jdaviz?

Is this in the context of MAST or something else?

**Comment by jrhastro** [comment]
I have not tried the dev version.  I am following the instructions on the readthedocs site (but have created a new environment specifically for jdaviz).

This is in the context of Roman work.  A couple of us in Roman INS were trying to install jdaviz and try some functionality in preparation for a potential Hack Day.

**Comment by pllim** [comment]
I can reproduce you problem and I managed to get it to go away by doing `conda install voila` instead of `pip install` everything. So please try this and let me know if it fixes things for you.

```
pip uninstall voila
conda install voila
```

Just say "yes" to everything.

**Comment by pllim** [comment]
`conda` sometimes works better when there are non-Python stuff involved in the stack.

**Comment by jrhastro** [comment]
The uninstall ran smoothly but the conda install failed.  Here is the output of the 2 commands above:

```
$ pip uninstall voila
Found existing installation: voila 0.3.3
Uninstalling voila-0.3.3:
  Would remove:
    /Users/jhargis/anaconda3/envs/jdaviz/bin/voila
    /Users/jhargis/anaconda3/envs/jdaviz/etc/jupyter/jupyter_notebook_config.d/voila.json
    /Users/jhargis/anaconda3/envs/jdaviz/etc/jupyter/jupyter_server_config.d/voila.json
    /Users/jhargis/anaconda3/envs/jdaviz/etc/jupyter/nbconfig/notebook.d/voila.json
    /Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/voila-0.3.3.dist-info/*
    /Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/voila/*
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/install.json
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/package.json
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/schemas/@voila-dashboards/jupyterlab-preview/package.json.orig
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/schemas/@voila-dashboards/jupyterlab-preview/plugin.json
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/static/643.999197bbd8ad4b2ee222.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/static/97.25065296abef311c4455.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/static/remoteEntry.0d414ba26cb02af927ee.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/static/style.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/labextensions/@voila-dashboards/jupyterlab-preview/static/third-party-licenses.json
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/nbextensions/voila/extension.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/404.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/browser-open.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/error.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/jupyter_widgets.html.j2
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/log.macro.html.j2
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/page.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/spinner.macro.html.j2
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/07173fb77d2ee655811499d40c8388e7.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/07281897a98a61c3733e1670f82a9fd5.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/1.voila.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/2.voila.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/3d580bd561716bfb1f0b4fdd7063a802.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/4c74e33b0feb1fdbda49403a5e7ed604.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/5589d1a8fc62be6613020ef2fa13e410.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/72815766b08ca24d4d29ad1f5d4ecb45.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/77dbcee3c3d9a82a0c04a4ae7992b895.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/7e83626ba8bf2d20dc41565f1e6d0afc.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/9995de4787f908d8237dba7007f6c3fe.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/b80e08d5a79acbd1fafb1ca6f3515664.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/bc3af04f9a671fcabd6498042c57478f.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/bc42125861bd5bfc8686deeb612dcbb3.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/c9423d5dc9d82a38ca215f74e9cdd9f2.woff
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/main.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/require.min.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/static/voila.js
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/tree.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/base/voila_setup.macro.html.j2
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/classic/index.html.j2
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/classic/static/labvariables.css
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/classic/static/materialcolors.css
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/lab/browser-open.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/lab/error.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/lab/index.html.j2
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/lab/page.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/lab/tree.html
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/reveal/index.html.j2
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/reveal/static/labvariables.css
    /Users/jhargis/anaconda3/envs/jdaviz/share/jupyter/voila/templates/reveal/static/materialcolors.css
Proceed (Y/n)? y
  Successfully uninstalled voila-0.3.3
(jdaviz) sundial:jdaviz jhargis$ conda install voila
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - voila

Current channels:

  - http://ssb.stsci.edu/astroconda/osx-64
  - http://ssb.stsci.edu/astroconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by pllim** [comment]
Try this: `conda install voila -c conda-forge`

p.s. You should really remove astroconda from your `.condarc` file.

**Comment by jrhastro** [comment]
I ran the new install command and get the following error.  The browser hangs with the "Executing cell 1 of 1".

```
(jdaviz) sundial:jdaviz jhargis$ jdaviz ./manga-8485-1901-LOGCUBE.fits.gz --layout=cubeviz
[Voila] Using /var/folders/wq/b0ymy3v15253byc7kntj80xc0001n8/T to store connection files
[Voila] Storing connection files in /var/folders/wq/b0ymy3v15253byc7kntj80xc0001n8/T/voila_zcdu4kh9.
[Voila] Serving static files from /Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/voila/static.
[Voila] Voilà is running at:
http://localhost:8866/
[Voila] WARNING | Notebook notebook.ipynb is not trusted
[Voila] Kernel started: 3fd80a30-6ee0-448e-9f61-9d97f4be07e4
/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/auth/decorator.py:66: FutureWarning: The Tornado web application does not have an 'authorizer' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an authorizer to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/653740cbad7ce0c8a8752ce83e4d3c2c754b13cb/jupyter_server/serverapp.py#L234-L256
  warnings.warn(
ERROR:tornado.application:Uncaught exception GET /api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 335, in get
    await res
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
ERROR:tornado.application:Uncaught exception GET /api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 335, in get
    await res
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
ERROR:tornado.application:Uncaught exception GET /api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 335, in get
    await res
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
ERROR:tornado.application:Uncaught exception GET /api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 335, in get
    await res
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
ERROR:tornado.application:Uncaught exception GET /api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 335, in get
    await res
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
ERROR:tornado.application:Uncaught exception GET /api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 335, in get
    await res
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
ERROR:tornado.application:Uncaught exception GET /api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3fd80a30-6ee0-448e-9f61-9d97f4be07e4/channels?session_id=ab4ccc87-860c-4a2f-87ac-b0177e3d855a', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 335, in get
    await res
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "/Users/jhargis/anaconda3/envs/jdaviz/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
```

**Comment by pllim** [comment]
Can you please try this?

1. Modify your `~/.condarc` channel settings to the following:

```
channel_priority: strict
channels:
  - defaults
  - conda-forge
```

2. `conda deactivate` (and make sure you are back in `base` env)
3. Create another new environment and activate it.
4. `conda install jupyter notebook voila`
5. `pip install jdaviz` (if you want to use `--no-cache-dir` here, you can)

If you still encounter errors, I'll have to ask someone with Big Sur machine.
