### ISSUE TITLE
CI failing with ipyvue FileNotFoundError

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1196]
Last successful log sample: https://github.com/spacetelescope/jdaviz/runs/5661939687?check_suite_focus=true

Failed log sample: https://github.com/spacetelescope/jdaviz/runs/5683120647?check_suite_focus=true (This job used to succeed but now fails when rerun)

First noticed around 2022-03-24 4:34 PM (US Eastern). No new upstream released detected in `pip freeze`.

```
py39-test-alldeps-cov run-test: commands[1] | pytest --pyargs jdaviz /home/runner/work/jdaviz/jdaviz/docs --cov jdaviz --cov-config=/home/runner/work/jdaviz/jdaviz/setup.cfg --remote-data
ImportError while loading conftest '/home/runner/work/jdaviz/jdaviz/conftest.py'.
../../conftest.py:1: in <module>
    from jdaviz import __version__
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/jdaviz/__init__.py:10: in <module>
    from jdaviz.app import *  # noqa
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/jdaviz/app.py:56: in <module>
    ipyvue.register_component_from_file(None, 'j-tooltip',
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/ipyvue/VueComponentRegistry.py:40: in register_component_from_file
    with open(file_name) as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/jdaviz/jdaviz/.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/jdaviz/components/tooltip.vue'
```

**Comment by pllim** [comment]
@mariobuikhuizen , have you seen error like this before over at ipyvue world? Any idea what is going on? This job used to succeed before I restarted it, so I am pretty sure this failure is not caused by this package.

**Comment by pllim** [comment]
Maybe this is a CI provider server problem that will resolve itself? Another job in the same build failed with a completely different error...

https://github.com/spacetelescope/jdaviz/runs/5683120836?check_suite_focus=true

```
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/runner/work/jdaviz/jdaviz/.tox/py310-test-devdeps/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/importlib/__init__.py", line [126](https://github.com/spacetelescope/jdaviz/runs/5683120836?check_suite_focus=true#step:6:126), in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/pip-build-env-6xwtjskx/overlay/lib/python3.10/site-packages/jupyter_packaging/__init__.py", line 6, in <module>
    from .setupbase import *
  File "/tmp/pip-build-env-6xwtjskx/overlay/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 37, in <module>
    from setuptools.config import StaticModule
ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/tmp/pip-build-env-6xwtjskx/overlay/lib/python3.10/site-packages/setuptools/config/__init__.py)
```

**Comment by pllim** [comment]
Okay, it is not you, it's us... See #1198.
