### ISSUE TITLE
Imviz Line Profile plot not showing in voila

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jdaviz#1202]
Workflow to reproduce:

1. `jdaviz --layout=imviz someimage.fits`
2. Open up Line Profile plugin.
3. Press "l". You see that X and Y get updated but no plot is showing.

Voila won't run on WSL2 and I have a hard time getting Jdaviz to install natively on Windows because my stuff is split into two disks. So, I need someone else to confirm this bug. It might just be my weird setup or it might be a real bug.

The `bqplot` stuff seems to work fine on Aperture photometry plugin, though this one draws two plots, not just one.

There are some errors/warnings on the browser dev console for me but I have no idea if they are related or not.

```
Unchecked runtime.lastError: The message port closed before a response was received.

Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel,
fallback to fetching individual model state. Reason: Control comm was closed too early

vue.min.js:6 TypeError: Cannot read properties of null (reading 'classList')
    at a.mounted (eval at <anonymous> (:8867/voila/nbextensions/jupyter-vue/nodeps.js:2:158829), <anonymous>:39:60)
    at y (:8867/voila/nbextensions/jupyter-vue/nodeps.js:2:159817)
    at a.mounted (:8867/voila/nbextensions/jupyter-vue/nodeps.js:2:160911)
    at He (vue.min.js:6:11397)
    at Yt (vue.min.js:6:25339)
    at Object.insert (vue.min.js:6:20368)
    at k (vue.min.js:6:60187)
    at a.__patch__ (vue.min.js:6:61547)
    at a.e._update (vue.min.js:6:34519)
    at a.r (vue.min.js:6:68168)
```

I also see this on the terminal:

```
WARNING:tornado.general:403 GET /voila/static/voila.js.map (::1): voila.js.map is not in root static directory
WARNING:tornado.general:403 GET /voila/static/voila.js.map (::1): voila.js.map is not in root static directory
```

[🐱](https://jira.stsci.edu/browse/JDAT-2267)

**Comment by pllim** [comment]
Not an issue anymore.
