### ISSUE TITLE
CLI interface gives complicated traceback instead of simple error if invalid file given

### ISSUE THREAD

**Issue by eteq** [spacetelescope/jdaviz#96]
If I do ``jdaviz --layout=cubeviz /not/actually/a/file``, the result is the traceback I've copied below. That's not ideal because the poor user who doesn't regularly look at tracebacks will see that and think it's an error in the software instead of an invalid path.  Instead it would be better if they see a friendly message at the command line and maybe something in the UI itself that tells them the path isn't loadable.

Note this *may* require an update to glue to get a more useful error out - e.g. it probably should be an `IOError` instead of just an `Exception`, but that's not mandatory for addressing this hopefully.

```
from jdaviz.app import Application
from glue.core import Data
app = Application(configuration='cubeviz')
data = app.load_data('/home/erik/none')
app
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/src/glue/glue/core/application_base.py in wrapper(*args, **kwargs)
     22             try:
---> 23                 return func(*args, **kwargs)
     24             except Exception as e:

~/src/glue/glue/core/application_base.py in load_data(self, paths, auto_merge, *
*kwargs)
    196         for path in paths:
--> 197             result = load_data(path)
    198             if isinstance(result, BaseData):

~/src/glue/glue/core/data_factories/helpers.py in load_data(path, factory, **kwa
rgs)
    261         if factory is None:
--> 262             raise KeyError("Don't know how to open file: %s" % path)
    263

KeyError: "Don't know how to open file: /home/erik/none"

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-1-47addfb53162> in <module>
      2 from glue.core import Data
      3 app = Application(configuration='cubeviz')
----> 4 data = app.load_data('/home/erik/none')
      5 app

~/src/jdaviz/jdaviz/app.py in load_data(self, path)
    107
    108     def load_data(self, path):
--> 109         self._application_handler.load_data(path)
    110
    111         # Attempt to link the data

~/src/glue/glue/core/application_base.py in wrapper(*args, **kwargs)
     26                 detail = str(traceback.format_exc())
     27                 self = args[0]
---> 28                 self.report_error(m, detail)
     29         return wrapper
     30     return decorator

~/src/glue/glue/core/application_base.py in report_error(self, message, detail)
    253             Longer context about the error
    254         """
--> 255         raise Exception(message + "(" + detail + ")")
    256
    257     def do(self, command):

Exception: Could not load data
"Don't know how to open file: /home/erik/none"(Traceback (most recent call last)
:
  File "/home/erik/src/glue/glue/core/application_base.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/home/erik/src/glue/glue/core/application_base.py", line 197, in load_da
ta
    result = load_data(path)
  File "/home/erik/src/glue/glue/core/data_factories/helpers.py", line 262, in l
oad_data
    raise KeyError("Don't know how to open file: %s" % path)
KeyError: "Don't know how to open file: /home/erik/none"
)
Exception: Could not load data
"Don't know how to open file: /home/erik/none"(Traceback (most recent call last)
:
  File "/home/erik/src/glue/glue/core/application_base.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/home/erik/src/glue/glue/core/application_base.py", line 197, in load_da
ta
    result = load_data(path)
  File "/home/erik/src/glue/glue/core/data_factories/helpers.py", line 262, in l
oad_data
    raise KeyError("Don't know how to open file: %s" % path)
KeyError: "Don't know how to open file: /home/erik/none"
)
```

**Comment by pllim** [comment]
I think this is not an issue anymore.

```
$ jdaviz --layout=cubeviz asdasd.fits 
Usage: jdaviz [OPTIONS] FILENAME
Try 'jdaviz --help' for help.

Error: Invalid value for 'FILENAME': Path 'asdasd.fits' does not exist.
```
